### PR TITLE
Please add the below NeurIPS publication

### PR DESCRIPTION
**Pull request by charan223**
Our paper, a recent NeurIPS publication,

1) Provides a good survey of fairness algorithms in the deep learning space 
2) Explains the social impact of biases in discussion, conclusion, supplementary material sections of the paper
3) Provides a novel dataset and has a codebase with all fairness models, metrics in one location
4) We perform the most extensive analysis of modern deep fairness algorithms on how their bias detection and mitigation capabilities.

Hence, I added our paper to all relevant sections in the README.

### CODE REVIEW

**Comment by KaiWeiChang** [comment]
Thank you for your contribution. Could you put the paper only under one major category to avoid duplication? 

Thanks

**Comment by charan223** [comment]
Currently, I have modified it to add it under the "Surveys" and "Data, models & metrics" sections. 

I believe it is suitable to be in both sections, as it provides a detailed survey. And has a codebase of multiple models, its own dataset + a standard dataset, all the fairness metrics. 

But if you think it should only be in "Surveys", I can change it

**Comment by KaiWeiChang** [comment]
Thanks, I did a quick read. Your paper is more suitable for "Data, models & metrics". Survey papers would focus on discussion of literature and they go beyond usual related work and discussion sections. 

Btw, although your paper is interesting, I'm not sure if it is suitable for this paper list. Our paper list is for NLP fairness papers and we collected papers focusing on language processing applications. I saw your paper mostly discusses image and census datasets, and their properties are quite different from language data.

**Comment by charan223** [comment]
Added it only in the "Data, models & metrics" section.

I believe the adversarial models we studied can be helpful in language applications too. The wholesome study performed, code provided will be a good addition to fairness work in general :)

**Pull request merged**
